name: CMake

on: 
  push:
    paths: 
      - ".github/workflows/test-cmake.yml"
      - "dist/**"
      - "action.yml"
      - "test/**"

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            COMPILER: gcc
            PLATFORM: 20.04
          - os: windows-2019
            COMPILER: msvc
            PLATFORM: 2019
          - os: windows-2019
            COMPILER: mingw
            PLATFORM: 2019

    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      uses: ./
      id: install-boost
      with:
        boost_version: 1.78.0
        platform_version: ${{matrix.PLATFORM}}
        toolset: ${{matrix.COMPILER}}

    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      if: ${{runner.os == 'Windows' && matrix.COMPILER == 'mingw'}}

    - name: Configure CMake mingw
      shell: bash
      working-directory: test
      run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBoost_LIBRARY_DIRS="${{steps.install-boost.outputs.BOOST_ROOT}}/lib" -G "MinGW Makefiles" -B build
      if: ${{matrix.COMPILER == 'mingw'}}
      env:
        BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}

    - name: Configure CMake
      shell: bash
      working-directory: test
      run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBoost_LIBRARY_DIRS="${{steps.install-boost.outputs.BOOST_ROOT}}/lib" -B build
      if: ${{matrix.COMPILER != 'mingw'}}
      env:
        BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}
    - name: Build
      working-directory: test/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
